version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7
    ports: ["6379:6379"]

  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports: ["9092:9092"]

  bot:
    build: ./bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      PG_DSN_NATIVE: "dbname=${POSTGRES_DB} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} host=postgres port=5432"
      REDIS_URL: ${REDIS_URL}
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}
      DEFAULT_TZ: ${DEFAULT_TZ}
    depends_on: [postgres, redis, kafka]
    
  scheduler:
    build: ./bot
    command: ["python","-u","worker_scheduler.py"]
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      PG_DSN_NATIVE: "dbname=${POSTGRES_DB} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} host=postgres port=5432"
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}
    depends_on: [postgres, kafka]

  sender:
    build: ./bot
    command: ["python","-u","worker_sender.py"]
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}
    depends_on: [kafka]

volumes:
  pgdata: